"""Parse and merge the dev-time legacy (pre-changelog) hash chain dataset.

The static dataset data/legacy_chains.json is generated by tools/generate_legacy_chains.py from the ZZZ-Mod-Fixer reference modules and holds one transition per character for hash updates that predate the upstream changelog; labels are either arrow pairs like "1.0 -> 1.1" or single-version tokens like "1.0" (single-sided dated updates, no target version recorded in the reference log). This module turns it into ChangeEntry rows with their own chronological index range and shifts the real changelog's indices past them, so chain resolution walks legacy steps first and changelog steps after.
"""

import json
import re
from pathlib import Path

from .model import ChangeEntry, HASH_RE
from .repo import data_dir

_LABEL_RE = re.compile(r"^\s*(?P<va>[\d.]+[A-Za-z]*)(?:\s*(?:->|→)\s*(?P<vb>[\d.]+[A-Za-z]*))?")
_INF = float("inf")


def legacy_chains_path() -> Path:
    """Static dataset: <project root>/data/legacy_chains.json (dev-time generated)."""
    return data_dir("legacy_chains.json")


def _version_key(token: str) -> tuple[float, str]:
    """Sort key for one version token like "1.5A": numeric part first."""
    numeric = re.match(r"[\d.]+", token)
    try:
        number = float(numeric.group(0)) if numeric else _INF
    except ValueError:
        number = _INF
    return number, token


def _label_sort_key(label: str) -> tuple[tuple[float, str], tuple[float, str]]:
    """Chronological sort key for one label like "1.5A -> 1.5B".

    Single-version labels like "1.5A" (single-sided dated updates) parse as
    from-version only and sort as (1.5A, 1.5A).  Unparseable labels sort last.
    """
    match = _LABEL_RE.match(label)
    if match is None:
        return (_INF, ""), (_INF, "")
    va = _version_key(match.group("va"))
    vb = match.group("vb")
    return va, _version_key(vb) if vb else va


def parse_legacy_chains(path: Path, first_index: int = 1) -> list[ChangeEntry]:
    """Parse the harvested pre-2.0 transitions into chronologically ordered ChangeEntry objects.

    Entries are grouped by version_label and version_index is assigned first_index...first_index+N-1 in the order distinct labels sort by their parsed (from-version, to-version) key — letter suffixes like "1.5A -> 1.5B" are accepted and single-version labels like "1.0" sort as (1.0, 1.0) — so every legacy step sorts strictly before the real changelog. first_index defaults to 1; when load_fixer_data also ingests the pcdata dataset it renumbers legacy indexes to start above the pcdata ordinals. Entries keep their per-character attribution for hint disambiguation, and role is "legacy".
    """
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    grouped: dict[str, list[ChangeEntry]] = {}
    if isinstance(data, list):
        for item in data:
            if not isinstance(item, dict):
                continue
            from_hash = item.get("from")
            to_hash = item.get("to")
            if not isinstance(from_hash, str) or not isinstance(to_hash, str):
                continue
            if not HASH_RE.fullmatch(from_hash) or not HASH_RE.fullmatch(to_hash):
                continue
            raw_characters = item.get("characters")
            characters = (
                [str(name) for name in raw_characters]
                if isinstance(raw_characters, list)
                else []
            )
            raw_label = item.get("label")
            label = raw_label if isinstance(raw_label, str) else ""
            grouped.setdefault(label, []).append(
                ChangeEntry(
                    from_hash=from_hash.lower(),
                    to_hash=to_hash.lower(),
                    characters=characters,
                    role="legacy",
                    version_label=label,
                )
            )
    result: list[ChangeEntry] = []
    for position, (_label, entries) in enumerate(
        sorted(grouped.items(), key=lambda pair: _label_sort_key(pair[0])),
        start=first_index,
    ):
        for entry in entries:
            entry.version_index = position
        result.extend(entries)
    return result


def merge_entries(legacy: list[ChangeEntry], real: list[ChangeEntry]) -> list[ChangeEntry]:
    """Shift the real changelog's version_index beyond the legacy steps and concatenate ascending.

    The shift is the highest legacy version_index (0 for empty legacy), not the count of distinct legacy labels, so it stays correct when legacy is renumbered to start above the pcdata ordinals.
    """
    shift = max((entry.version_index for entry in legacy), default=0)
    combined = list(legacy)
    for entry in real:
        entry.version_index += shift
        combined.append(entry)
    return combined
